[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "9vEtaZya9ePodChCbc2LGu1Wf41uJqSCZfJUSKwTT6Ds"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/beatricethelisma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
